name: refineapp
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  splashscreen: ^1.3.5
  get: ^4.1.4
  firebase_core: ^1.0.3
  firebase_analytics: ^7.1.1
  firebase_auth: ^1.1.2
  cloud_firestore: ^1.0.4
  flutter_spinkit: ^4.1.2+1
  firebase_storage: ^8.0.5
  image_picker: ^0.7.4
  get_it: ^4.0.1
  flutter_audio_recorder: ^0.5.5


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3
  # if you are using latest flutter please update your flutter_svg package to ^0.18.*
  flutter_svg: ^0.19.1 # help us to use SVG in our app
  provider: ^5.0.0 # for State management
  audioplayers: ^0.16.1
  path_provider: ^1.6.1


dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
   - assets/images/
   - assets/icons/

  fonts:
    - family: muli
      fonts:
        - asset: assets/fonts/muli/Muli.ttf
        - asset: assets/fonts/muli/Muli-Bold.ttf
          weight: 700
        - asset: assets/fonts/muli/Muli-Light.ttf
          weight: 300

dependency_overrides:
  flutter_audio_recorder: ^0.5.5